DOAN_BANHANG_VY/Areas/Admin/Controllers/CthoadonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DOAN_BANHANG_VY.Data;
using DOAN_BANHANG_VY.Models;
using Microsoft.AspNetCore.Authorization;

namespace DOAN_BANHANG_VY.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class CthoadonsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CthoadonsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Cthoadons

        // GET: Admin/Cthoadons/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cthoadon = await _context.Cthoadons
                .Include(c => c.MaHdNavigation)
                .Include(c => c.MaMhNavigation)
                .FirstOrDefaultAsync(m => m.MaCthd == id);
            if (cthoadon == null)
            {
                return NotFound();
            }

            return View(cthoadon);
        }

        // GET: Admin/Cthoadons/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cthoadon = await _context.Cthoadons.FindAsync(id);
            if (cthoadon == null)
            {
                return NotFound();
            }
            ViewData["MaHd"] = new SelectList(_context.Hoadons, "MaHd", "MaHd", cthoadon.MaHd);
            ViewData["MaMh"] = new SelectList(_context.Mathangs, "MaMh", "Ten", cthoadon.MaMh);
            return View(cthoadon);
        }

        // POST: Admin/Cthoadons/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaCthd,MaHd,MaMh,DonGia,Solung,ThanhTien")] Cthoadon cthoadon)
        {
            if (id != cthoadon.MaCthd)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    cthoadon.ThanhTien = cthoadon.Solung * cthoadon.DonGia;

                    _context.Update(cthoadon);
                    await _context.SaveChangesAsync();
                    var cthdUpdate = _context.Cthoadons.Where(x => x.MaHd.Equals(cthoadon.MaHd)).ToList();
                    int tong = 0;
                    foreach( var item in cthdUpdate)
                    {
                        tong += item.Solung * item.DonGia;
                    }
                    var hoadon = await _context.Hoadons.FirstOrDefaultAsync(x => x.MaHd == cthoadon.MaHd);
                    hoadon.TongTien = tong;
                    _context.Update(cthoadon);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CthoadonExists(cthoadon.MaCthd))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                // Lấy giá trị của Mahd từ cthoadon
                int mahd1 = cthoadon.MaHd;

                // Tạo một đối tượng RouteValueDictionary để chứa thông tin chuyển hướng
                var routeValues1 = new RouteValueDictionary
                {   
                { "controller", "HoaDons" },   // Controller muốn chuyển hướng đến
                { "action", "Details" },       // Action muốn chuyển hướng đến
                { "id", mahd1 }                  // Tham số id
                };

                // Sử dụng RedirectToAction với đối số routeValues
                return RedirectToAction("Details", "HoaDons", routeValues1);
            }
            ViewData["MaHd"] = new SelectList(_context.Hoadons, "MaHd", "MaHd", cthoadon.MaHd);
            ViewData["MaMh"] = new SelectList(_context.Mathangs, "MaMh", "Ten", cthoadon.MaMh);
            // Lấy giá trị của Mahd từ cthoadon
            int mahd = cthoadon.MaHd;

            // Tạo một đối tượng RouteValueDictionary để chứa thông tin chuyển hướng
            var routeValues = new RouteValueDictionary
            {
                { "controller", "HoaDons" },   // Controller muốn chuyển hướng đến
                { "action", "Details" },       // Action muốn chuyển hướng đến
                { "id", mahd }                  // Tham số id
            };

            // Sử dụng RedirectToAction với đối số routeValues
            return RedirectToAction("Details", "HoaDons", routeValues);
        }

        // GET: Admin/Cthoadons/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cthoadon = await _context.Cthoadons
                .Include(c => c.MaHdNavigation)
                .Include(c => c.MaMhNavigation)
                .FirstOrDefaultAsync(m => m.MaCthd == id);
            if (cthoadon == null)
            {
                return NotFound();
            }

            return View(cthoadon);
        }

        // POST: Admin/Cthoadons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cthoadon = await _context.Cthoadons.FindAsync(id);
            if (cthoadon != null)
            {
                _context.Cthoadons.Remove(cthoadon);
            }
            int mahd = cthoadon.MaHd;
            await _context.SaveChangesAsync();
            var cthdUpdate = _context.Cthoadons.Where(x => x.MaHd.Equals(cthoadon.MaHd)).ToList();
            int tong = 0;
            foreach (var item in cthdUpdate)
            {
                tong += item.Solung * item.DonGia;
            }
            var hoadon = await _context.Hoadons.FirstOrDefaultAsync(x => x.MaHd == cthoadon.MaHd);
            hoadon.TongTien = tong;
            _context.Update(cthoadon);
            await _context.SaveChangesAsync();
            // Lấy giá trị của Mahd từ cthoadon

            // Tạo một đối tượng RouteValueDictionary để chứa thông tin chuyển hướng
            var routeValues = new RouteValueDictionary
            {
                { "controller", "HoaDons" },   // Controller muốn chuyển hướng đến
                { "action", "Details" },       // Action muốn chuyển hướng đến
                { "id", mahd }                  // Tham số id
            };

            // Sử dụng RedirectToAction với đối số routeValues
            return RedirectToAction("Details", "HoaDons", routeValues);
        }

        private bool CthoadonExists(int id)
        {
            return _context.Cthoadons.Any(e => e.MaCthd == id);
        }
    }
}

DOAN_BANHANG_VY/Areas/Admin/Controllers/HoadonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DOAN_BANHANG_VY.Data;
using DOAN_BANHANG_VY.Models;
using Microsoft.AspNetCore.Authorization;
using DOAN_BANHANG_VY.DTO;
using Newtonsoft.Json;
using Microsoft.Data.SqlClient;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace DOAN_BANHANG_VY.Areas.Admin.Controllers
{
    [Area("Admin")]
	[Authorize]

	public class HoadonsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HoadonsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Hoadons
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Hoadons.Include(h => h.MaKhNavigation);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Admin/Hoadons/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hoadon = await _context.Hoadons
                .Include(h => h.MaKhNavigation)
                .Include(cthd => cthd.Cthoadons)
                .ThenInclude(mh => mh.MaMhNavigation)
                .FirstOrDefaultAsync(m => m.MaHd == id);
            if (hoadon == null)
            {
                return NotFound();
            }

            return View(hoadon);
        }

        // GET: Admin/Hoadons/Create
        public async Task<IActionResult> Create()
        {
            ViewData["MaKh"] = new SelectList(_context.Khachhangs, "MaKh", "Ten");
            ViewBag.CART = GetCartItems();
            ViewBag.DSSP = await _context.Mathangs.ToListAsync();
            return View();
        }

        // POST: Admin/Hoadons/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaHd,Ngay,TongTien,MaKh,TrangThai")] Hoadon hoadon)
        {
            if (ModelState.IsValid)
            {
                _context.Add(hoadon);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaKh"] = new SelectList(_context.Khachhangs, "MaKh", "Ten", hoadon.MaKh);
            return View(hoadon);
        }

        // GET: Admin/Hoadons/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hoadon = await _context.Hoadons.FindAsync(id);
            if (hoadon == null)
            {
                return NotFound();
            }
            ViewData["MaKh"] = new SelectList(_context.Khachhangs, "MaKh", "Ten", hoadon.MaKh);
            return View(hoadon);
        }

        // POST: Admin/Hoadons/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaHd,Ngay,TongTien,MaKh,TrangThai")] Hoadon hoadon)
        {
            if (id != hoadon.MaHd)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hoadon);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HoadonExists(hoadon.MaHd))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaKh"] = new SelectList(_context.Khachhangs, "MaKh", "Ten", hoadon.MaKh);
            return View(hoadon);
        }

        // GET: Admin/Hoadons/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hoadon = await _context.Hoadons
                .Include(h => h.MaKhNavigation)
                .FirstOrDefaultAsync(m => m.MaHd == id);
            if (hoadon == null)
            {
                return NotFound();
            }

            return View(hoadon);
        }

        // POST: Admin/Hoadons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hoadon = await _context.Hoadons.FindAsync(id);
            if (hoadon != null)
            {
                _context.Hoadons.Remove(hoadon);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HoadonExists(int id)
        {
            return _context.Hoadons.Any(e => e.MaHd == id);
        }
        List<CartItems> GetCartItems()
        {
            var session = HttpContext.Session;
            string jsoncart = session.GetString("CT");
            if (jsoncart != null)
            {
                return JsonConvert.DeserializeObject<List<CartItems>>(jsoncart);
            }
            return new List<CartItems>();
        }
        void RemoveCart()
        {
            var session = HttpContext.Session;
            session.Remove("CT");
        }
        //lưu danh sách cartitem giỏ hàng vào session
        bool SaveCartSession(List<CartItems> cartItems)
        {
            try
            {
                // Check if HttpContext is available
                if (HttpContext == null || HttpContext.Session == null)
                {
                    // Handle the situation where HttpContext or Session is not available
                    return false;
                }

                var session = HttpContext.Session;

                // Serialize cartItems to JSON
                string jsonCart = JsonConvert.SerializeObject(cartItems);

                // Save JSON string to the session
                session.SetString("CT", jsonCart);

                return true;
            }
            catch (Exception ex)
            {
                // Log the exception for troubleshooting purposes
                Console.Error.WriteLine($"Error saving cart session: {ex.Message}");
                Console.Error.WriteLine(ex.StackTrace); // Log the stack trace for more details
                return false;
            }
        }
        // Xóa session giỏ hàng
        void ClearCart()
        {
            var session = HttpContext.Session;
            session.Remove("CT");
        }

        // thêm hàng vào giỏ
        public async Task<IActionResult> AddToCart(int id,DateTime Ngay , int MaKH)
        {
            try
            {
                var mathang = await _context.Mathangs.Include(x => x.MaDmNavigation).FirstOrDefaultAsync(m => m.MaMh == id);
                if (mathang == null)
                {
                    return NotFound("Sản phẩm không tồn tại");
                }
                var mathangdto = new MathangDTO();
                mathangdto.Ten = mathang.Ten;
                mathangdto.MaMh = id;
                mathangdto.GiaBan = mathang.GiaBan;
                mathangdto.GiaGoc = mathang.GiaGoc;
                mathangdto.SoLuong = 1;
                var cart = GetCartItems();
                var item = cart.Find(p => p.Mathang.MaMh == id);
                if (item != null)
                {
                    item.soluong++;
                }
                else
                {
                    cart.Add(new CartItems() { Mathang = mathangdto, soluong = mathangdto.SoLuong });
                }
                var success = SaveCartSession(cart);
                if (success)
                {
                    ViewData["ngaytao"] = Ngay;
                    ViewData["MaKh"] = new SelectList(_context.Khachhangs, "MaKh", "Ten", MaKH != 0? MaKH : null);
                    ViewData["kh"] = MaKH;
                    TempData["SuccessMessage"] = "Thêm thành công";
                    return RedirectToAction(nameof(Create));
                }
                else
                {
                    return NotFound();
                }
            }
            catch (Exception ex) { return BadRequest("An error occurred while processing the request."); }

        }

        public IActionResult RemoveItem(int id, int soluong, DateTime ngaytao, int MaKH)
        {
            var cart = GetCartItems();
            var item = cart.Find(p => p.Mathang.MaMh == id);
            if (item != null)
            {
                cart.Remove(item);
            }
            SaveCartSession(cart);
            ViewData["ngaytao"] = ngaytao;
            ViewData["MaKh"] = new SelectList(_context.Khachhangs, "MaKh", "Ten", MaKH);
            TempData["SuccessMessage"] = "Thêm thành công";
            return RedirectToAction(nameof(Create));
        }

        public IActionResult UpdateItem(int id, int quantity, DateTime ngaytao, int MaKH)
        {
            var cart = GetCartItems();
            var item = cart.Find(p => p.Mathang.MaMh == id);
            if (item != null)
            {
                item.soluong = quantity;
            }
            SaveCartSession(cart);
            ViewData["ngaytao"] = ngaytao;

DOAN_BANHANG_VY/Areas/Admin/Views/Hoadons/Create.cshtml
@model DOAN_BANHANG_VY.Models.Hoadon

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="pagetitle">
    <h1>Thêm mới hóa đơn</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="index">Hóa đơn</a></li>
            <li class="breadcrumb-item active">Thêm mới</li>
        </ol>
    </nav>
</div><!-- End Page Title -->
<section class="section dashboard">
<div class="row">
    <div class="col-md-3">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                  
                        <label asp-for="Ngay" class="control-label"></label>
                        @{
                            // Lấy ngày hiện tại
                            DateTime currentDate = DateTime.Now;
                            // Định dạng ngày tháng năm (dd/MM/yyyy) và gán vào input
                            string formattedDate = currentDate.ToString("dd/MM/yyyy");
                        }
                    <input asp-for="Ngay" class="form-control" data-provide="datepicker" data-date-format="dd/mm/yyyy" value="@formattedDate" />
                        <span asp-validation-for="Ngay" class="text-danger"></span>
             </div>
            <div class="form-group">
                <label asp-for="TongTien" class="control-label"></label>
                <input asp-for="TongTien" class="form-control" />
                <span asp-validation-for="TongTien" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaKh" class="control-label"></label>
                <select asp-for="MaKh" class ="form-control" asp-items="ViewBag.MaKh"></select>
            </div>
            <div class="form-group">
                <label asp-for="TrangThai" class="control-label"></label>
                    <select asp-for="TrangThai" class="form-control">
                        <option value="0">Chưa xác nhận</option>
                        <option value="1">Xác nhận</option>
                        <option value="2">Đang giao hàng</option>
                        <option value="3">Đã giao hàng</option>
                        <option value="4">Đơn hàng đã bị hủy bởi khách hàng</option>
                        <option value="5">Đơn hàng đã bị hủy bởi cửa hàng</option>
                    </select>
                <span asp-validation-for="TrangThai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div class="col-md-9">
            <div class="row">
                <div class="col-md-4">
                    <label for="searchProduct">Tìm kiếm:</label>
                    <input type="text" id="searchProduct" oninput="filterProducts()" placeholder="Nhập để tìm kiếm sản phẩm..." class="form-control">
                </div>
                <div class="col-md-8">
                    <ul id="productList" class="mh-50" style="display: none;">
                        <div class="overflow-auto  bg-light"
                             style="max-width: 100%; max-height: 300px;">
                            <code>
                                @foreach (var item in ViewBag.DSSP)
                                {
                                    <!-- Your product list items will go here -->
                                <li class="product-item" data-productname="@item.Ten">
                                <div class="row">
                                    <div class="col-md-4">

                                        <img src="~/images/sanpham/@item.HinhAnh" style="width:100px; height:130px" />
                                    </div>
                                    <div class="col-md-4">
                                           @item.Ten
                                    </div>
                                    <div class="col-md-4">
                                        @if(item.GiaBan != item.GiaGoc)
                                        {
                                            @item.GiaBan.ToString("N0")
                                         }
                                         else
                                         {
                                             @item.GiaGoc.ToString("N0")
                                         }
                                         đ
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-8"></div>
                                    <div class="col-md-4">
                                        <form asp-action="AddToCart" asp-route-id="@item.MaMh">
                                            <div class="form-group">
                                                <input name="MaKH" class="form-control" type="hidden" id="id_an" />
                                                <input name="ngaytao" class="form-control" type="hidden" id="ngay_an"/>
                                            </div>
                                            <input type="submit" class="btn btn-success" value="Chọn"/>
                                        </form>
                                    </div>

                                </div>
                            </li>
                           }
                        </code>
                </div>
                </ul>
            </div>
        </div>


        <script>
            function filterProducts() {
                var input, filter, ul, li, i, txtValue;
                input = document.getElementById("searchProduct");
                filter = input.value.toUpperCase();
                ul = document.getElementById("productList");
                li = ul.getElementsByClassName("product-item");

                // Toggle the visibility of the product list based on user input
                ul.style.display = filter.length > 0 ? "block" : "none";

                for (i = 0; i < li.length; i++) {
                    txtValue = li[i].getAttribute("data-productname");
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        li[i].style.display = "";
                    } else {
                        li[i].style.display = "none";
                    }
                }
            }
        </script>
    </div>
</div>


<div class="col-md-12">
        <h4 class="text-info">Thông tin đơn hàng</h4>
        <table class="table">
            <tr>
                <th>STT</th>
                <th>Tên hàng</th>
                <th>Giá bán</th>
                <th>Số lượng</th>
                <th>Thành tiền</th>
            </tr>
            @if (ViewBag.CART != null)
            {
                int stt = 1;
                int thanhtien = 0;
                int tongtien = 0;
                @foreach (var i in ViewBag.CART)
                {
                    thanhtien = i.Mathang.GiaBan * i.soluong;
                    tongtien += thanhtien;
                    <tr>
                        <td>
                            @(stt++)
                        </td>
                        <td>
                            @i.Mathang.Ten
                        </td>
                        <td>
                            @(i.Mathang.GiaBan.ToString("n0")) VNĐ
                        </td>
                        <td>
                            <form asp-action="UpdateItem" method="post" asp-route-id="@i.Mathang.MaMh">
                                <div class="row">
                                    <div class="col">
                                        <input name="quantity" type="number" class="form-control" value="@i.soluong"/>
                                    </div>
                                    <div class="col">
                                        <input class="btn btn-warning" type="submit" value="Cập nhật" />
                                    </div>
                                </div>
                            </form>
                        </td>
                        <td>
                            @(thanhtien.ToString("n0")) VNĐ
                        </td>
                        <td>
                            <a asp-asp-controller="Home" asp-action="RemoveItem" asp-route-id="@i.Mathang.MaMh" class="btn btn-danger">Xóa</a>
                        </td>
                    </tr>
                }
                <tr>
                    <td colspan="4" class="text-end fw-bold"> Thành tiền</td>
                    <td colspan="2"><strong class="text-danger">@(tongtien.ToString("n0")) VNĐ</strong></td>
                </tr>
            }
        </table>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>
        $(document).ready(function () {
            // Lấy giá trị mặc định của MaKh và gán vào id_an
            var defaultMaKhValue = $('select[name="MaKh"]').val();
            console.log(defaultMaKhValue);
            $('#id_an').val(defaultMaKhValue);

            // Theo dõi sự thay đổi của trường Ngay
            $('input[name="Ngay"]').on('change', function () {
                var ngayValue = $(this).val();
                $('#ngay_an').val(ngayValue);
            });

            // Theo dõi sự thay đổi của trường MaKh
            $('select[name="MaKh"]').on('change', function () {
                var maKhValue = $(this).val();
                $('#id_an').val(maKhValue);
            });
        });
    </script>

<div>
    <a asp-action="Index">Quay về danh sách</a>
</div>
</section>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DOAN_BANHANG_VY/Areas/Admin/Views/Hoadons/Details.cshtml
@model DOAN_BANHANG_VY.Models.Hoadon

@{
    ViewData["Title"] = "Xem chi tiết hóa đơn";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="pagetitle">
    <h1>Xem chi tiết</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="index">Hóa đơn</a></li>
            <li class="breadcrumb-item active">Xem chi tiết</li>
        </ol>
    </nav>
</div><!-- End Page Title -->
<section class="section dashboard">

<div>
    <dl class="row">
        <div class="row">
            <div class="col-md-4">
                Mã Hóa Đơn: @Model.MaHd
            </div>
            <div class="col-md-4">
                    Ngày tạo: @Model.Ngay

            </div>   
            <div class="col-md-4">
                    @if (Model.TrangThai == 0)
                    {
                        <text>Chưa xác nhận</text>
                    }
                    else if (Model.TrangThai == 1)
                    {
                        <text>Xác nhận</text>
                    }
                    else if (Model.TrangThai == 2)
                    {
                        <text>Đang giao hàng</text>
                    }
                    else if (Model.TrangThai == 3)
                    {
                        <text>Đã giao hàng</text>
                    }
                    else if (Model.TrangThai == 4)
                    {
                        <text>Đơn hàng đã bị hủy bởi khách hàng</text>
                    }
                    else if (Model.TrangThai == 5)
                    {
                        <text>Đơn hàng đã bị hủy bởi cửa hàng</text>
                    }
                </div>
        </div>
            <div class="row">
                <div class="col-md-4">
                    Khách hàng: @Model.MaKhNavigation.Ten
                </div>
                <div class="col-md-4">
                    Điện thoại: @Model.MaKhNavigation.DienThoai
                </div>
                <div class="col-md-4">
                    Email: @Model.MaKhNavigation.Email
                </div>
            </div>
            <div class="row">
                <div class="justify-content-center">
                    <table class="table table-responsive table-hover">
                        <thead class="thead-light">
                            <tr>
                                <th>STT</th>
                                <th>Tên sản phẩm</th>
                                <th>Số lượng</th>
                                <th>Đơn giá</th>
                                <th>Thành tiền</th                      
                                  <th></th>
                                  <th></th>

                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int stt = 1;
                            }

                            @foreach (var item in Model.Cthoadons)
                            {
                                <tr>
                                    <td>@(stt++)</td>
                                    <td>@(item.MaMhNavigation.Ten)</td>
                                    <td>@item.Solung</td>
                                    <td>@item.DonGia.ToString("N0") đ</td>
                                    <td>@item.ThanhTien.ToString("N0") đ</td>
                                     <td>
                                         <a asp-action="Edit" asp-controller="Cthoadons" asp-route-id="@item.MaCthd" class="btn btn-outline-info"><i class="bi bi-pencil-square"></i></a>
                                     </td>
                                     <td>
                                         <a asp-action="Delete" asp-controller="Cthoadons" asp-route-id="@item.MaCthd" class="btn btn-outline-danger"><i class="bi bi-trash"></i></a>
                                     </td>
                                </tr>
                            }
                            <tr>
                                <td colspan="4">Tổng tiền: </td>
                                <td colspan="1" class="text-danger"> @Model.TongTien.ToString("N0") đ</td>
                            </tr>
                        </tbody>
                    </table>

                </div>
            </div>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.MaHd">Chỉnh sửa</a> |
    <a asp-action="Index">Quay về danh sách</a>
</div>
</section>